// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCHAe3WX9yN-UCVir5FaDGZed47GZBL8',
    appId: '1:206976544108:web:5e90f8bfedd78ecbf15749',
    messagingSenderId: '206976544108',
    projectId: 'e-commerceapp-1f902',
    authDomain: 'e-commerceapp-1f902.firebaseapp.com',
    storageBucket: 'e-commerceapp-1f902.appspot.com',
    measurementId: 'G-BN5YPKYJHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFCZs4eAS8FPIckgFV0Zo5fUiipv00cc',
    appId: '1:206976544108:android:2f59cffcdbbde792f15749',
    messagingSenderId: '206976544108',
    projectId: 'e-commerceapp-1f902',
    storageBucket: 'e-commerceapp-1f902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNo-2y-nvIKFYKMttQB___64-XyZGNQzU',
    appId: '1:206976544108:ios:6cf646d2d476dd71f15749',
    messagingSenderId: '206976544108',
    projectId: 'e-commerceapp-1f902',
    storageBucket: 'e-commerceapp-1f902.appspot.com',
    iosClientId: '206976544108-c2qmi1mckgpflg2qsmgibbel3uahgqai.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNo-2y-nvIKFYKMttQB___64-XyZGNQzU',
    appId: '1:206976544108:ios:6cf646d2d476dd71f15749',
    messagingSenderId: '206976544108',
    projectId: 'e-commerceapp-1f902',
    storageBucket: 'e-commerceapp-1f902.appspot.com',
    iosClientId: '206976544108-c2qmi1mckgpflg2qsmgibbel3uahgqai.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStart',
  );
}
