// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJxh2idWdd1be4qNKYtCNxFwhmpKQ6qPw',
    appId: '1:397043748364:web:ff20d64d496c68d974e829',
    messagingSenderId: '397043748364',
    projectId: 'myfirstapp-603a9',
    authDomain: 'myfirstapp-603a9.firebaseapp.com',
    storageBucket: 'myfirstapp-603a9.appspot.com',
    measurementId: 'G-RWQ15HR6M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYqOOm2X4_h4-2L9RhAeKkgP-Vcjz9-hA',
    appId: '1:397043748364:android:b5482bee6028c2c274e829',
    messagingSenderId: '397043748364',
    projectId: 'myfirstapp-603a9',
    storageBucket: 'myfirstapp-603a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZhswQntebkvfnHaGl8826aPB8JjIhsys',
    appId: '1:397043748364:ios:85fce3500f664c5f74e829',
    messagingSenderId: '397043748364',
    projectId: 'myfirstapp-603a9',
    storageBucket: 'myfirstapp-603a9.appspot.com',
    iosClientId: '397043748364-m79k50m6pc8rn9l30ef7ou6co6d0qeje.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZhswQntebkvfnHaGl8826aPB8JjIhsys',
    appId: '1:397043748364:ios:85fce3500f664c5f74e829',
    messagingSenderId: '397043748364',
    projectId: 'myfirstapp-603a9',
    storageBucket: 'myfirstapp-603a9.appspot.com',
    iosClientId: '397043748364-m79k50m6pc8rn9l30ef7ou6co6d0qeje.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStart',
  );
}
